aligner: "star_salmon"
gencode: true
igenomes_ignore: true
trimmer: "trimgalore"
min_trimmed_reads: 10000
remove_ribo_rna: false
with_umi: false
gtf_group_features: "gene_id"
gtf_extra_attributes: "gene_name,gene_type"
featurecounts_group_type: "gene_type"
featurecounts_feature_type: "exon"
min_mapped_reads: 5
skip_bbsplit: true
skip_linting: false
skip_trimming: false
skip_quantification_merge: false
skip_markduplicates: false
skip_bigwig: true
skip_stringtie: true
skip_fastqc: false
skip_preseq: true
skip_dupradar: false
skip_qualimap: false
skip_rseqc: false
skip_biotype_qc: false
skip_deseq2_qc: false
skip_multiqc: false
save_reference: true
save_trimmed: false
save_align_intermeds: false
