from __future__ import annotations

from pathlib import Path
from typing import Annotated

import typer

from rnaseq_mvp.cli import DEFAULT_WORKSPACE, app
from rnaseq_mvp.constants import ExitCode
from rnaseq_mvp.public_download import PublicDownloadError, download_public_fastqs
from rnaseq_mvp.public_prepare import PublicPrepareError, prepare_public_dataset


@app.command("public-download")
def public_download(
    manifest: Annotated[
        Path,
        typer.Option(
            "--manifest",
            help="FASTQ manifest generated by public-prepare.",
        ),
    ],
    max_attempts: Annotated[
        int,
        typer.Option(
            "--max-attempts",
            help="Maximum download attempts per FASTQ file.",
        ),
    ] = 3,
) -> None:
    """Download and verify public FASTQ files from a generated manifest."""
    try:
        result = download_public_fastqs(
            manifest_tsv=manifest,
            max_attempts=max_attempts,
        )
    except (PublicDownloadError, OSError) as error:
        typer.echo(str(error), err=True)
        raise typer.Exit(code=int(ExitCode.PREPARE)) from error

    typer.echo("Public FASTQ download completed.")
    typer.echo(f"FASTQ manifest: {result.manifest_tsv}")
    typer.echo(f"FASTQ files: {result.file_count}")
    typer.echo(f"Downloaded: {result.downloaded_count}")
    typer.echo(f"Reused: {result.reused_count}")
    typer.echo(f"Repaired: {result.repaired_count}")


@app.command("public-fetch")
def public_fetch(
    accession: Annotated[
        str,
        typer.Option(
            "--accession",
            help=(
                "Public accession. Accepts PRJNA/SRP/ERP directly, or a GEO "
                "Series accession such as GSE231509."
            ),
        ),
    ],
    dataset: Annotated[
        str,
        typer.Option(
            "--dataset",
            help="Dataset label for generated files, for example GSE231509.",
        ),
    ],
    run_id: Annotated[
        str,
        typer.Option(
            "--run-id",
            help="Prepared run identifier, for example GSE231509_COUNTS_ONLY_V1.",
        ),
    ],
    workspace: Annotated[
        Path,
        typer.Option("--workspace", help="Runtime workspace directory."),
    ] = DEFAULT_WORKSPACE,
    max_attempts: Annotated[
        int,
        typer.Option(
            "--max-attempts",
            help="Maximum download attempts per FASTQ file.",
        ),
    ] = 3,
) -> None:
    """Prepare public metadata and download all verified FASTQ files."""
    try:
        prepared = prepare_public_dataset(
            accession=accession,
            dataset=dataset,
            run_id=run_id,
            workspace=workspace,
        )
        downloaded = download_public_fastqs(
            manifest_tsv=prepared.manifest_tsv,
            max_attempts=max_attempts,
        )
    except (PublicPrepareError, PublicDownloadError, OSError) as error:
        typer.echo(str(error), err=True)
        raise typer.Exit(code=int(ExitCode.PREPARE)) from error

    typer.echo("Public dataset preparation and FASTQ download completed.")
    typer.echo(f"Query accession: {prepared.query_accession}")
    typer.echo(f"Resolved accession: {prepared.resolved_accession}")
    typer.echo(f"Layout: {prepared.layout}")
    typer.echo(f"Runs: {prepared.run_count}")
    typer.echo(f"FASTQ files: {downloaded.file_count}")
    typer.echo(f"Downloaded: {downloaded.downloaded_count}")
    typer.echo(f"Reused: {downloaded.reused_count}")
    typer.echo(f"Repaired: {downloaded.repaired_count}")
    typer.echo(f"ENA metadata: {prepared.metadata_tsv}")
    typer.echo(f"FASTQ manifest: {prepared.manifest_tsv}")
    typer.echo(f"Samplesheet: {prepared.samplesheet_csv}")
    typer.echo(f"Parameters: {prepared.params_yml}")
